
import type { Metadata } from "next";
import { Poppins } from 'next/font/google'
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { AuthProvider } from "@/hooks/use-auth";
import { ThemeProvider } from "@/components/theme-provider";
import Script from "next/script";

const poppins = Poppins({ 
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-body'
})

export const metadata: Metadata = {
  title: "Vibespace",
  description: "A modern social content sharing app.",
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable}`} suppressHydrationWarning>
      <head>
        <meta name="theme-color" content="#020817" />
      </head>
      <body className="font-body antialiased">
        <ThemeProvider>
          <AuthProvider>
              {children}
          </AuthProvider>
        </ThemeProvider>
        <Toaster />
        
        {/* Firebase SDK - Fetched from Firebase Hosting */}
        <Script src="/__/firebase/9.23.0/firebase-app-compat.js" strategy="beforeInteractive" />
        <Script src="/__/firebase/9.23.0/firebase-auth-compat.js" strategy="beforeInteractive" />
        <Script src="/__/firebase/9.23.0/firebase-firestore-compat.js" strategy="beforeInteractive" />
        <Script src="/__/firebase/9.23.0/firebase-storage-compat.js" strategy="beforeInteractive" />
        
        {/* This script is auto-generated by Firebase Hosting and contains your project's config */}
        <Script src="/__/firebase/init.js" strategy="beforeInteractive" />
      </body>
    </html>
  );
}
