
import {
  Home,
  Video,
  UserCircle,
  PlusSquare,
  Search,
  Heart,
  MessageCircle,
  MoreHorizontal,
  Send,
  Bookmark,
  ChevronLeft,
  Settings,
  Image as ImageIcon,
  LoaderCircle,
  X,
  Sparkles,
  ChevronRight,
  Bell,
  Lock,
  Star,
  EyeOff,
  UserX,
  FileText,
  AtSign,
  Repeat,
  History,
  Ban,
  MessageSquare,
  Plus,
  LogOut,
  Pencil,
  Camera,
  Grid,
  Menu,
  Play,
  Edit,
  HeartHandshake,
  DollarSign,
  UserSearch,
  type LucideIcon,
} from 'lucide-react';

export const Icons = {
  home: Home,
  reels: Video,
  profile: UserCircle,
  create: PlusSquare,
  search: Search,
  like: Heart,
  liked: HeartHandshake,
  comment: MessageCircle,
  more: MoreHorizontal,
  send: Send,
  bookmark: Bookmark,
  back: ChevronLeft,
  settings: Settings,
  image: ImageIcon,
  spinner: LoaderCircle,
  close: X,
  sparkles: Sparkles,
  chevronRight: ChevronRight,
  notifications: Bell,
  accountPrivacy: Lock,
  closeFriends: Star,
  blocked: Ban,
  hideStory: EyeOff,
  restrictedAccounts: UserX,
  hiddenWords: FileText,
  tagsAndMentions: AtSign,
  sharingAndReuse: Repeat,
  yourActivity: History,
  editProfile: UserCircle,
  edit: Edit,
  messages: MessageSquare,
  messagesAndStoryReplies: MessageSquare,
  plus: Plus,
  logout: LogOut,
  pencil: Pencil,
  camera: Camera,
  grid: Grid,
  menu: Menu,
  play: Play,
  dollar: DollarSign,
  billing: DollarSign,
  sponsor: Star,
  userSearch: UserSearch,
};

export type Icon = LucideIcon;
